import { Container } from "@/components/shared/container";
import { Header } from "@/components/shared/header";
import { Fotter } from "@/components/core/Footer";
import Catalog from "@/components/shared/catalog";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "FitZone | Account",
  description: "Generated by create next app",
};
export default function Account() {
  return (
    <Container className="w-full ">
      <Header />
      <Catalog />
      <div>
        <h1>Account</h1>
      </div>
      <Fotter />
    </Container>
  );
}
