import type { Metadata } from 'next'

import { Container } from '@/shared/sharedd/container'
import { Header } from '@/shared/sharedd/header'

import { Fotter } from '@/components/core/Footer'
import { Catalog } from '@/components/core/catalog/catalog'

export const metadata: Metadata = {
	title: 'FitZone | Account',
	description: 'Generated by create next app'
}
export default function Account() {
	return (
		<Container className='w-full'>
			<Header />
			<Catalog />
			<div>
				<h1>Account</h1>
			</div>
			<Fotter />
		</Container>
	)
}
